name: searxng-openwebui

services:
  redis:
    api: 3
    type: lando
    app_mount: false
    services:
      image: docker.io/valkey/valkey:8-alpine
      command: valkey-server --save 30 1 --loglevel warning
      volumes:
        - valkey-data2:/data

  searxng:
    api: 3
    type: lando
    ssl: true
    sslExpose: false
    scanner: false
    app_mount: false
    services:
      image: docker.io/searxng/searxng:latest
      command: /usr/local/searxng/entrypoint.sh 
      volumes:
        - ./searxng:/etc/searxng
        - searxng-data:/var/cache/searxng
      environment:
        SEARXNG_BASE_URL: https://search.lndo.site/

  open-webui:
    api: 3
    type: lando
    scanner: false
    app_mount: false
    ssl: true
    sslExpose: false
    services:
      image: ghcr.io/open-webui/open-webui:main
      command: bash start.sh
      volumes:
        - ~/.open-webui:/app/backend/data
      environment:
        WEBUI_AUTH: false
        OLLAMA_BASE_URL: http://ollama:11434

  llama-cpp:
    api: 3
    type: lando
    scanner: false
    app_mount: false
    ssl: false
    services:
      # User -rocm if you have an AMD GPU
      image: ghcr.io/ggml-org/llama.cpp:server-vulkan
      command: >
        /app/llama-server
        --model /models/Qwen3.6/Qwen3.6-35B-A3B-MTP-UD-Q5_K_XL.gguf
        --mmproj /models/Qwen3.6/mmproj-F16.gguf
        --gpu-layers all
        --ctx-size 524288
        --yarn-orig-ctx 262144
        --rope-scaling yarn
        --rope-scale 2
        --spec-type draft-mtp 
        --spec-draft-n-max 3
        --port 8395
        --temp 0.6
        --top-p 0.95
        --top-k 20
        --min-p 0.0
        --presence-penalty 1.5
        --flash-attn on 
        --cache-type-k q8_0 
        --cache-type-v q8_0 
        --alias qwen3.6-35b-unsloth
        --no-mmap
      volumes:
        - ~/gguf:/models
      environment:
        LLAMA_CACHE: unsloth/qwen3.6-35b-gguf

      devices:
        - /dev/kfd:/dev/kfd
        - /dev/dri:/dev/dri
      ports:
        - "8395:8395"

proxy:
  searxng:
    - search.lndo.site:8080
  open-webui:
    - open-webui.lndo.site:8080

#tooling:
#  ollama:
#    service: ollama
#    description: Run ollama CLI commands
#    cmd: ollama
